### ISSUE TITLE
Initial Organization of Website

### ISSUE THREAD

**Issue by lisambrown** [flatironinstitute/blastoSPIM_web#1]
Main Page

Title: Robust 3D Nuclear Instance Segmentation of the Early Mouse Embryo
Menu: dataset, model, paper, visualizations
keep text that is there: We introduce..
Top of page: gifs of GT/Sys Placeholder Header (see bottom of current page 1) 
caption: 
left: ground truth segmentation of nuclei in late blastocyst embryo
right: system segmentation of nuclei in same late blastocyst embryo
(two videos should be synchronized)
Under text: put fucci_sox_stack1 gif with caption:
Time lapse sequence of the nuclei in the early mouse embryo as acquired using a light-sheet microscope every 15 minutes.

 
 
Four links from menu on first page:
 
Dataset: (link to page currently from Preview and Download Data)
title of page: BlastoSPIM Dataset
text at top of page:
The BlastoSPIM dataset includes 573 fully annotated 3D images of nuclei in mouse embryos, each manually curated for annotation. Across all images, there are 11708 individual nuclear instances annotated and 116 annotated polar bodies. Not all of these 3D images come from different time series. For example, for one developing mouse embryo, we annotated 89 consecutive time-points, and for another embryo, we annotated 100 consecutive time-points. Both of these time-lapse annotations extend from the 16-cell stage to the approximately 64-cell stage. The total number of distinct embryos imaged and annotated is 31.
 
Model: 
title of page: BlastoSPIM Models
links to two models: early stage 3D Stardist model (8 to 64 nuclei)
                                    late stage 3D Stardist model (64 to 128 nuclei)
text at top of page 
We evaluated five neural network architectures to determine how to obtain the best instance segmentation on our dataset. 
(show Figure 1 from paper)
The results are summarized in the table below.
The model with the best performance was a 3D Stardist [reference to here: https://arxiv.org/abs/1908.03636)
--put table 1 from paper
 
Paper: 
"A novel ground truth dataset enables robust 3D nuclear instance segmentation in early mouse embryos"
 
(link to Hayden)
Hayden Nunley, et al.
 
 
Hayden Nunley, Binglun Shao,Prateek Grover, Jaspreet Singh,
Bradley Joyce, Rebecca Kim-Yip, Abraham Kohrman, Aaron Watters,
Zsombor Gal, Alison Kickuth, Madeleine Chalifoux,
Stanislav Shvartsman, Eszter Posfai, Lisa M. Brown 
 
Center for Computational Biology, Flatiron Institute - Simons Foundation, New York, United States of America
Department of Chemical and Biological Engineering, Princeton University, Princeton, New Jersey, United States of America
Department of Molecular Biology, Princeton University, Princeton, New Jersey, United States of America
The Lewis-Sigler Institute for Integrative Genomics, Princeton University, Princeton, New Jersey, United States of America
 
submitted to PLOS Computation Biology
 
Figure 3 from paper here
 
Visualizations: 
Title: Instance Segmentation Visualizations using BlastoSPIM
Text: Below are interactive visualization examples for mouse embryo nuclei
at the 8, 16, 32, 64, and 128 cell stage.
 
(the first four of these are now under: Segmentation detail Visualizations (bottom of page)
visualization of 8,16,32,64 and 100+ embryos - we need to give you the one for 100+

 

[BlastoSPIM__3D_instance_segmentation_of_nuclei_in_the_mouse_blastocyst_draft1 (2).pdf](https://github.com/flatironinstitute/blastoSPIM_web/files/10439981/BlastoSPIM__3D_instance_segmentation_of_nuclei_in_the_mouse_blastocyst_draft1.2.pdf)

**Comment by AaronWatters** [comment]
I broke these reqs into subtasks for individual tracking and discussion.
