### ISSUE TITLE
website improvement suggestions

### ISSUE THREAD

**Issue by lisambrster** [flatironinstitute/blastoSPIM_web#8]
page 1

I don't think you need the "Paper Fig3" in the caption for the figure.
The Microscopy Source Data - could be to the right of text describing the data with the
following caption: Light-sheet microscopy of early mouse embryo

We are submitting the paper to Developmental Cell (no longer to PLOS Biology)
- but I think you can leave out the submitted part and let's just a put a link
to the bioRxiv link as soon as Hayden submits.

I would make the paper title and authors - like it would be in a bibliography and put the institutions in smaller print.

**Comment by AaronWatters** [comment]
The link is still missing but the formatting is fixed.  I will add a link when it is available.
