### ISSUE TITLE
website improvement suggestions - after page 1

### ISSUE THREAD

**Issue by lisambrster** [flatironinstitute/blastoSPIM_web#9]
all the pages have text on the top left that shouldn't be there: Blastospim main entry page or json loaded - please remove this

on the dataset page - I would remove the "Series" header

on the model page - the figure should be the architecture figure (Figure 2) and table (Figure 5) from the paper attached here.
Please put the captions without specific reference to figure numbers in the paper.

I will have Hayden send you the two models so you can put in the real links.

For the visualization page:
Let's have the choice be 8, 16,32, 64, 128 nuclei stage (without the sequence name - which doesn't mean anything to the user, nucleus -> nuclei since plural here) - and similarly change the title of the visualization to exactly match this.
Let's change the "Select the segmentation" to "Please select the developmental stage of the embryo"
I would remove the download link - since you can download on the download page and I find it confusing here.
I think there is an issue in the visualization of the slices when you look at the bottom-most slice.

[BlastoSPIM__3D_instance_segmentation_of_nuclei_in_the_mouse_blastocyst_draft1 (4).pdf](https://github.com/flatironinstitute/blastoSPIM_web/files/10560274/BlastoSPIM__3D_instance_segmentation_of_nuclei_in_the_mouse_blastocyst_draft1.4.pdf)

**Comment by AaronWatters** [comment]
1) I think I removed the text that shouldn't be there (?)

2) series header hidden

3) vis page -- please let me know which timestamps in which series I should use exactly.  New issue https://github.com/flatironinstitute/blastoSPIM_web/issues/11

4) Download link in vis page removed.

5) Slicing issue -- I will look into this when I regenerate the data sets for the new timetamps (3)

6) Added architecture illustration and qualitative illustration to model page.

7) Wording adjusted above vis dropdown.

I think this either addresses or reissues all suggestions here.
